// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: common-proto/booking.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractRequest) Reset() {
	*x = ContractRequest{}
	mi := &file_common_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRequest) ProtoMessage() {}

func (x *ContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRequest.ProtoReflect.Descriptor instead.
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *ContractRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type InformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	WorkStatus    string                 `protobuf:"bytes,3,opt,name=work_status,json=workStatus,proto3" json:"work_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationResponse) Reset() {
	*x = InformationResponse{}
	mi := &file_common_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationResponse) ProtoMessage() {}

func (x *InformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationResponse.ProtoReflect.Descriptor instead.
func (*InformationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *InformationResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *InformationResponse) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *InformationResponse) GetWorkStatus() string {
	if x != nil {
		return x.WorkStatus
	}
	return ""
}

var File_common_proto_booking_proto protoreflect.FileDescriptor

const file_common_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x1acommon-proto/booking.proto\x12\fcommon_proto\"(\n" +
	"\x0fContractRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"|\n" +
	"\x13InformationResponse\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\x12\x1f\n" +
	"\vwork_status\x18\x03 \x01(\tR\n" +
	"workStatus2h\n" +
	"\x0eBookingService\x12V\n" +
	"\x12CheckBookingStatus\x12\x1d.common_proto.ContractRequest\x1a!.common_proto.InformationResponseB\x18Z\x16common-proto/bookingpbb\x06proto3"

var (
	file_common_proto_booking_proto_rawDescOnce sync.Once
	file_common_proto_booking_proto_rawDescData []byte
)

func file_common_proto_booking_proto_rawDescGZIP() []byte {
	file_common_proto_booking_proto_rawDescOnce.Do(func() {
		file_common_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_booking_proto_rawDesc), len(file_common_proto_booking_proto_rawDesc)))
	})
	return file_common_proto_booking_proto_rawDescData
}

var file_common_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_booking_proto_goTypes = []any{
	(*ContractRequest)(nil),     // 0: common_proto.ContractRequest
	(*InformationResponse)(nil), // 1: common_proto.InformationResponse
}
var file_common_proto_booking_proto_depIdxs = []int32{
	0, // 0: common_proto.BookingService.CheckBookingStatus:input_type -> common_proto.ContractRequest
	1, // 1: common_proto.BookingService.CheckBookingStatus:output_type -> common_proto.InformationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_booking_proto_init() }
func file_common_proto_booking_proto_init() {
	if File_common_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_booking_proto_rawDesc), len(file_common_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_booking_proto_goTypes,
		DependencyIndexes: file_common_proto_booking_proto_depIdxs,
		MessageInfos:      file_common_proto_booking_proto_msgTypes,
	}.Build()
	File_common_proto_booking_proto = out.File
	file_common_proto_booking_proto_goTypes = nil
	file_common_proto_booking_proto_depIdxs = nil
}
