// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: common-proto/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_common_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_common_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_common_proto_auth_proto protoreflect.FileDescriptor

const file_common_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x17common-proto/auth.proto\x12\fcommon_proto\"/\n" +
	"\x0eAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"+\n" +
	"\x0fAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Z\n" +
	"\vAuthService\x12K\n" +
	"\fCloseAccount\x12\x1c.common_proto.AccountRequest\x1a\x1d.common_proto.AccountResponseB\tZ\a/authpbb\x06proto3"

var (
	file_common_proto_auth_proto_rawDescOnce sync.Once
	file_common_proto_auth_proto_rawDescData []byte
)

func file_common_proto_auth_proto_rawDescGZIP() []byte {
	file_common_proto_auth_proto_rawDescOnce.Do(func() {
		file_common_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_auth_proto_rawDesc), len(file_common_proto_auth_proto_rawDesc)))
	})
	return file_common_proto_auth_proto_rawDescData
}

var file_common_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_auth_proto_goTypes = []any{
	(*AccountRequest)(nil),  // 0: common_proto.AccountRequest
	(*AccountResponse)(nil), // 1: common_proto.AccountResponse
}
var file_common_proto_auth_proto_depIdxs = []int32{
	0, // 0: common_proto.AuthService.CloseAccount:input_type -> common_proto.AccountRequest
	1, // 1: common_proto.AuthService.CloseAccount:output_type -> common_proto.AccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_auth_proto_init() }
func file_common_proto_auth_proto_init() {
	if File_common_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_auth_proto_rawDesc), len(file_common_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_auth_proto_goTypes,
		DependencyIndexes: file_common_proto_auth_proto_depIdxs,
		MessageInfos:      file_common_proto_auth_proto_msgTypes,
	}.Build()
	File_common_proto_auth_proto = out.File
	file_common_proto_auth_proto_goTypes = nil
	file_common_proto_auth_proto_depIdxs = nil
}
