// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: common-proto/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserSettingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EnableInApp     *bool                  `protobuf:"varint,2,opt,name=enable_in_app,json=enableInApp,proto3,oneof" json:"enable_in_app,omitempty"`
	EnableEmail     *bool                  `protobuf:"varint,3,opt,name=enable_email,json=enableEmail,proto3,oneof" json:"enable_email,omitempty"`
	EnablePush      *bool                  `protobuf:"varint,4,opt,name=enable_push,json=enablePush,proto3,oneof" json:"enable_push,omitempty"`
	MutedCategories []string               `protobuf:"bytes,5,rep,name=muted_categories,json=mutedCategories,proto3" json:"muted_categories,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserSettingRequest) Reset() {
	*x = CreateUserSettingRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserSettingRequest) ProtoMessage() {}

func (x *CreateUserSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateUserSettingRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserSettingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserSettingRequest) GetEnableInApp() bool {
	if x != nil && x.EnableInApp != nil {
		return *x.EnableInApp
	}
	return false
}

func (x *CreateUserSettingRequest) GetEnableEmail() bool {
	if x != nil && x.EnableEmail != nil {
		return *x.EnableEmail
	}
	return false
}

func (x *CreateUserSettingRequest) GetEnablePush() bool {
	if x != nil && x.EnablePush != nil {
		return *x.EnablePush
	}
	return false
}

func (x *CreateUserSettingRequest) GetMutedCategories() []string {
	if x != nil {
		return x.MutedCategories
	}
	return nil
}

type NewJobForCategoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CategoryId       int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	JobTitle         string                 `protobuf:"bytes,3,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CustomerId       string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	RecipientUserIds []string               `protobuf:"bytes,6,rep,name=recipient_user_ids,json=recipientUserIds,proto3" json:"recipient_user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NewJobForCategoryRequest) Reset() {
	*x = NewJobForCategoryRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewJobForCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewJobForCategoryRequest) ProtoMessage() {}

func (x *NewJobForCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewJobForCategoryRequest.ProtoReflect.Descriptor instead.
func (*NewJobForCategoryRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NewJobForCategoryRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *NewJobForCategoryRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *NewJobForCategoryRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *NewJobForCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewJobForCategoryRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *NewJobForCategoryRequest) GetRecipientUserIds() []string {
	if x != nil {
		return x.RecipientUserIds
	}
	return nil
}

type ApplyForJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,4,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	BidAmount     float64                `protobuf:"fixed64,5,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyForJobRequest) Reset() {
	*x = ApplyForJobRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyForJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyForJobRequest) ProtoMessage() {}

func (x *ApplyForJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyForJobRequest.ProtoReflect.Descriptor instead.
func (*ApplyForJobRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyForJobRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplyForJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ApplyForJobRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyForJobRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *ApplyForJobRequest) GetBidAmount() float64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

func (x *ApplyForJobRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type AcceptJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ApplicationId  string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ContractId     string                 `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FreelancerId   string                 `protobuf:"bytes,5,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	AcceptedAmount float64                `protobuf:"fixed64,6,opt,name=accepted_amount,json=acceptedAmount,proto3" json:"accepted_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptJobRequest) Reset() {
	*x = AcceptJobRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJobRequest) ProtoMessage() {}

func (x *AcceptJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJobRequest.ProtoReflect.Descriptor instead.
func (*AcceptJobRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AcceptJobRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AcceptJobRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *AcceptJobRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AcceptJobRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *AcceptJobRequest) GetAcceptedAmount() float64 {
	if x != nil {
		return x.AcceptedAmount
	}
	return 0
}

type UpdateStatusContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,4,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,5,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusContractRequest) Reset() {
	*x = UpdateStatusContractRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusContractRequest) ProtoMessage() {}

func (x *UpdateStatusContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusContractRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusContractRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *UpdateStatusContractRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateStatusContractRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateStatusContractRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *UpdateStatusContractRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *UpdateStatusContractRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type NotificationDisputeForAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisputeId     string                 `protobuf:"bytes,1,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ContractId    string                 `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	AdminUserIds  []string               `protobuf:"bytes,7,rep,name=admin_user_ids,json=adminUserIds,proto3" json:"admin_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationDisputeForAdminRequest) Reset() {
	*x = NotificationDisputeForAdminRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDisputeForAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDisputeForAdminRequest) ProtoMessage() {}

func (x *NotificationDisputeForAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationDisputeForAdminRequest.ProtoReflect.Descriptor instead.
func (*NotificationDisputeForAdminRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationDisputeForAdminRequest) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

func (x *NotificationDisputeForAdminRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *NotificationDisputeForAdminRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NotificationDisputeForAdminRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *NotificationDisputeForAdminRequest) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *NotificationDisputeForAdminRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NotificationDisputeForAdminRequest) GetAdminUserIds() []string {
	if x != nil {
		return x.AdminUserIds
	}
	return nil
}

type NotificationDisputeResolutionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DisputeId      string                 `protobuf:"bytes,1,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	ContractId     string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FreelancerId   string                 `protobuf:"bytes,4,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	ResolutionType string                 `protobuf:"bytes,5,opt,name=resolution_type,json=resolutionType,proto3" json:"resolution_type,omitempty"`
	AdminNote      string                 `protobuf:"bytes,6,opt,name=admin_note,json=adminNote,proto3" json:"admin_note,omitempty"`
	RefundAmount   float64                `protobuf:"fixed64,7,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	PayoutAmount   float64                `protobuf:"fixed64,8,opt,name=payout_amount,json=payoutAmount,proto3" json:"payout_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationDisputeResolutionRequest) Reset() {
	*x = NotificationDisputeResolutionRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDisputeResolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDisputeResolutionRequest) ProtoMessage() {}

func (x *NotificationDisputeResolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationDisputeResolutionRequest.ProtoReflect.Descriptor instead.
func (*NotificationDisputeResolutionRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationDisputeResolutionRequest) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

func (x *NotificationDisputeResolutionRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NotificationDisputeResolutionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *NotificationDisputeResolutionRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *NotificationDisputeResolutionRequest) GetResolutionType() string {
	if x != nil {
		return x.ResolutionType
	}
	return ""
}

func (x *NotificationDisputeResolutionRequest) GetAdminNote() string {
	if x != nil {
		return x.AdminNote
	}
	return ""
}

func (x *NotificationDisputeResolutionRequest) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *NotificationDisputeResolutionRequest) GetPayoutAmount() float64 {
	if x != nil {
		return x.PayoutAmount
	}
	return 0
}

type ChangeBalanceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId     string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionType   string                 `protobuf:"bytes,3,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	TransactionStatus string                 `protobuf:"bytes,4,opt,name=transaction_status,json=transactionStatus,proto3" json:"transaction_status,omitempty"`
	Amount            float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter      *float64               `protobuf:"fixed64,6,opt,name=balance_after,json=balanceAfter,proto3,oneof" json:"balance_after,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChangeBalanceRequest) Reset() {
	*x = ChangeBalanceRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBalanceRequest) ProtoMessage() {}

func (x *ChangeBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBalanceRequest.ProtoReflect.Descriptor instead.
func (*ChangeBalanceRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeBalanceRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ChangeBalanceRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *ChangeBalanceRequest) GetTransactionStatus() string {
	if x != nil {
		return x.TransactionStatus
	}
	return ""
}

func (x *ChangeBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChangeBalanceRequest) GetBalanceAfter() float64 {
	if x != nil && x.BalanceAfter != nil {
		return *x.BalanceAfter
	}
	return 0
}

type NotiResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotificationIds []string               `protobuf:"bytes,3,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotiResponse) Reset() {
	*x = NotiResponse{}
	mi := &file_common_proto_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotiResponse) ProtoMessage() {}

func (x *NotiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotiResponse.ProtoReflect.Descriptor instead.
func (*NotiResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{8}
}

func (x *NotiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotiResponse) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

type DispatchNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	SourceService string                 `protobuf:"bytes,6,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,7,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchNotificationRequest) Reset() {
	*x = DispatchNotificationRequest{}
	mi := &file_common_proto_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchNotificationRequest) ProtoMessage() {}

func (x *DispatchNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchNotificationRequest.ProtoReflect.Descriptor instead.
func (*DispatchNotificationRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{9}
}

func (x *DispatchNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DispatchNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DispatchNotificationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DispatchNotificationRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DispatchNotificationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DispatchNotificationRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *DispatchNotificationRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type DispatchNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	SourceService string                 `protobuf:"bytes,7,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,8,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchNotificationResponse) Reset() {
	*x = DispatchNotificationResponse{}
	mi := &file_common_proto_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchNotificationResponse) ProtoMessage() {}

func (x *DispatchNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchNotificationResponse.ProtoReflect.Descriptor instead.
func (*DispatchNotificationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_notification_proto_rawDescGZIP(), []int{10}
}

func (x *DispatchNotificationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DispatchNotificationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DispatchNotificationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DispatchNotificationResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DispatchNotificationResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DispatchNotificationResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DispatchNotificationResponse) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *DispatchNotificationResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *DispatchNotificationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_common_proto_notification_proto protoreflect.FileDescriptor

const file_common_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fcommon-proto/notification.proto\x12\fcommon_proto\"\x88\x02\n" +
	"\x18CreateUserSettingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\renable_in_app\x18\x02 \x01(\bH\x00R\venableInApp\x88\x01\x01\x12&\n" +
	"\fenable_email\x18\x03 \x01(\bH\x01R\venableEmail\x88\x01\x01\x12$\n" +
	"\venable_push\x18\x04 \x01(\bH\x02R\n" +
	"enablePush\x88\x01\x01\x12)\n" +
	"\x10muted_categories\x18\x05 \x03(\tR\x0fmutedCategoriesB\x10\n" +
	"\x0e_enable_in_appB\x0f\n" +
	"\r_enable_emailB\x0e\n" +
	"\f_enable_push\"\xe0\x01\n" +
	"\x18NewJobForCategoryRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x1b\n" +
	"\tjob_title\x18\x03 \x01(\tR\bjobTitle\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x12recipient_user_ids\x18\x06 \x03(\tR\x10recipientUserIds\"\xcb\x01\n" +
	"\x12ApplyForJobRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rfreelancer_id\x18\x04 \x01(\tR\ffreelancerId\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x05 \x01(\x01R\tbidAmount\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"\xe0\x01\n" +
	"\x10AcceptJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1f\n" +
	"\vcontract_id\x18\x03 \x01(\tR\n" +
	"contractId\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rfreelancer_id\x18\x05 \x01(\tR\ffreelancerId\x12'\n" +
	"\x0faccepted_amount\x18\x06 \x01(\x01R\x0eacceptedAmount\"\xd9\x01\n" +
	"\x1bUpdateStatusContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rfreelancer_id\x18\x04 \x01(\tR\ffreelancerId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x05 \x01(\tR\tnewStatus\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\tR\tupdatedBy\"\x87\x02\n" +
	"\"NotificationDisputeForAdminRequest\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x01 \x01(\tR\tdisputeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vcontract_id\x18\x03 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\frequester_id\x18\x04 \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12$\n" +
	"\x0eadmin_user_ids\x18\a \x03(\tR\fadminUserIds\"\xbe\x02\n" +
	"$NotificationDisputeResolutionRequest\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x01 \x01(\tR\tdisputeId\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rfreelancer_id\x18\x04 \x01(\tR\ffreelancerId\x12'\n" +
	"\x0fresolution_type\x18\x05 \x01(\tR\x0eresolutionType\x12\x1d\n" +
	"\n" +
	"admin_note\x18\x06 \x01(\tR\tadminNote\x12#\n" +
	"\rrefund_amount\x18\a \x01(\x01R\frefundAmount\x12#\n" +
	"\rpayout_amount\x18\b \x01(\x01R\fpayoutAmount\"\x84\x02\n" +
	"\x14ChangeBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12)\n" +
	"\x10transaction_type\x18\x03 \x01(\tR\x0ftransactionType\x12-\n" +
	"\x12transaction_status\x18\x04 \x01(\tR\x11transactionStatus\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12(\n" +
	"\rbalance_after\x18\x06 \x01(\x01H\x00R\fbalanceAfter\x88\x01\x01B\x10\n" +
	"\x0e_balance_after\"m\n" +
	"\fNotiResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10notification_ids\x18\x03 \x03(\tR\x0fnotificationIds\"\xe6\x01\n" +
	"\x1bDispatchNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12%\n" +
	"\x0esource_service\x18\x06 \x01(\tR\rsourceService\x12!\n" +
	"\freference_id\x18\a \x01(\tR\vreferenceId\"\x8f\x02\n" +
	"\x1cDispatchNotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12%\n" +
	"\x0esource_service\x18\a \x01(\tR\rsourceService\x12!\n" +
	"\freference_id\x18\b \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status2\xce\x06\n" +
	"\x13NotificationService\x12W\n" +
	"\x11CreateUserSetting\x12&.common_proto.CreateUserSettingRequest\x1a\x1a.common_proto.NotiResponse\x12W\n" +
	"\x11NewJobForCategory\x12&.common_proto.NewJobForCategoryRequest\x1a\x1a.common_proto.NotiResponse\x12K\n" +
	"\vApplyForJob\x12 .common_proto.ApplyForJobRequest\x1a\x1a.common_proto.NotiResponse\x12G\n" +
	"\tAcceptJob\x12\x1e.common_proto.AcceptJobRequest\x1a\x1a.common_proto.NotiResponse\x12]\n" +
	"\x14UpdateStatusContract\x12).common_proto.UpdateStatusContractRequest\x1a\x1a.common_proto.NotiResponse\x12k\n" +
	"\x1bNotificationDisputeForAdmin\x120.common_proto.NotificationDisputeForAdminRequest\x1a\x1a.common_proto.NotiResponse\x12o\n" +
	"\x1dNotificationDisputeResolution\x122.common_proto.NotificationDisputeResolutionRequest\x1a\x1a.common_proto.NotiResponse\x12O\n" +
	"\rChangeBalance\x12\".common_proto.ChangeBalanceRequest\x1a\x1a.common_proto.NotiResponse\x12a\n" +
	"\bDispatch\x12).common_proto.DispatchNotificationRequest\x1a*.common_proto.DispatchNotificationResponseB\x11Z\x0f/notificationpbb\x06proto3"

var (
	file_common_proto_notification_proto_rawDescOnce sync.Once
	file_common_proto_notification_proto_rawDescData []byte
)

func file_common_proto_notification_proto_rawDescGZIP() []byte {
	file_common_proto_notification_proto_rawDescOnce.Do(func() {
		file_common_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_notification_proto_rawDesc), len(file_common_proto_notification_proto_rawDesc)))
	})
	return file_common_proto_notification_proto_rawDescData
}

var file_common_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_notification_proto_goTypes = []any{
	(*CreateUserSettingRequest)(nil),             // 0: common_proto.CreateUserSettingRequest
	(*NewJobForCategoryRequest)(nil),             // 1: common_proto.NewJobForCategoryRequest
	(*ApplyForJobRequest)(nil),                   // 2: common_proto.ApplyForJobRequest
	(*AcceptJobRequest)(nil),                     // 3: common_proto.AcceptJobRequest
	(*UpdateStatusContractRequest)(nil),          // 4: common_proto.UpdateStatusContractRequest
	(*NotificationDisputeForAdminRequest)(nil),   // 5: common_proto.NotificationDisputeForAdminRequest
	(*NotificationDisputeResolutionRequest)(nil), // 6: common_proto.NotificationDisputeResolutionRequest
	(*ChangeBalanceRequest)(nil),                 // 7: common_proto.ChangeBalanceRequest
	(*NotiResponse)(nil),                         // 8: common_proto.NotiResponse
	(*DispatchNotificationRequest)(nil),          // 9: common_proto.DispatchNotificationRequest
	(*DispatchNotificationResponse)(nil),         // 10: common_proto.DispatchNotificationResponse
}
var file_common_proto_notification_proto_depIdxs = []int32{
	0,  // 0: common_proto.NotificationService.CreateUserSetting:input_type -> common_proto.CreateUserSettingRequest
	1,  // 1: common_proto.NotificationService.NewJobForCategory:input_type -> common_proto.NewJobForCategoryRequest
	2,  // 2: common_proto.NotificationService.ApplyForJob:input_type -> common_proto.ApplyForJobRequest
	3,  // 3: common_proto.NotificationService.AcceptJob:input_type -> common_proto.AcceptJobRequest
	4,  // 4: common_proto.NotificationService.UpdateStatusContract:input_type -> common_proto.UpdateStatusContractRequest
	5,  // 5: common_proto.NotificationService.NotificationDisputeForAdmin:input_type -> common_proto.NotificationDisputeForAdminRequest
	6,  // 6: common_proto.NotificationService.NotificationDisputeResolution:input_type -> common_proto.NotificationDisputeResolutionRequest
	7,  // 7: common_proto.NotificationService.ChangeBalance:input_type -> common_proto.ChangeBalanceRequest
	9,  // 8: common_proto.NotificationService.Dispatch:input_type -> common_proto.DispatchNotificationRequest
	8,  // 9: common_proto.NotificationService.CreateUserSetting:output_type -> common_proto.NotiResponse
	8,  // 10: common_proto.NotificationService.NewJobForCategory:output_type -> common_proto.NotiResponse
	8,  // 11: common_proto.NotificationService.ApplyForJob:output_type -> common_proto.NotiResponse
	8,  // 12: common_proto.NotificationService.AcceptJob:output_type -> common_proto.NotiResponse
	8,  // 13: common_proto.NotificationService.UpdateStatusContract:output_type -> common_proto.NotiResponse
	8,  // 14: common_proto.NotificationService.NotificationDisputeForAdmin:output_type -> common_proto.NotiResponse
	8,  // 15: common_proto.NotificationService.NotificationDisputeResolution:output_type -> common_proto.NotiResponse
	8,  // 16: common_proto.NotificationService.ChangeBalance:output_type -> common_proto.NotiResponse
	10, // 17: common_proto.NotificationService.Dispatch:output_type -> common_proto.DispatchNotificationResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_notification_proto_init() }
func file_common_proto_notification_proto_init() {
	if File_common_proto_notification_proto != nil {
		return
	}
	file_common_proto_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_proto_notification_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_notification_proto_rawDesc), len(file_common_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_notification_proto_goTypes,
		DependencyIndexes: file_common_proto_notification_proto_depIdxs,
		MessageInfos:      file_common_proto_notification_proto_msgTypes,
	}.Build()
	File_common_proto_notification_proto = out.File
	file_common_proto_notification_proto_goTypes = nil
	file_common_proto_notification_proto_depIdxs = nil
}
