// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: common-proto/notification.proto

package notificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_CreateUserSetting_FullMethodName             = "/common_proto.NotificationService/CreateUserSetting"
	NotificationService_NewJobForCategory_FullMethodName             = "/common_proto.NotificationService/NewJobForCategory"
	NotificationService_ApplyForJob_FullMethodName                   = "/common_proto.NotificationService/ApplyForJob"
	NotificationService_AcceptJob_FullMethodName                     = "/common_proto.NotificationService/AcceptJob"
	NotificationService_UpdateStatusContract_FullMethodName          = "/common_proto.NotificationService/UpdateStatusContract"
	NotificationService_NotificationDisputeForAdmin_FullMethodName   = "/common_proto.NotificationService/NotificationDisputeForAdmin"
	NotificationService_NotificationDisputeResolution_FullMethodName = "/common_proto.NotificationService/NotificationDisputeResolution"
	NotificationService_ChangeBalance_FullMethodName                 = "/common_proto.NotificationService/ChangeBalance"
	NotificationService_Dispatch_FullMethodName                      = "/common_proto.NotificationService/Dispatch"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	CreateUserSetting(ctx context.Context, in *CreateUserSettingRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	NewJobForCategory(ctx context.Context, in *NewJobForCategoryRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	ApplyForJob(ctx context.Context, in *ApplyForJobRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	AcceptJob(ctx context.Context, in *AcceptJobRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	UpdateStatusContract(ctx context.Context, in *UpdateStatusContractRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	NotificationDisputeForAdmin(ctx context.Context, in *NotificationDisputeForAdminRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	NotificationDisputeResolution(ctx context.Context, in *NotificationDisputeResolutionRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	ChangeBalance(ctx context.Context, in *ChangeBalanceRequest, opts ...grpc.CallOption) (*NotiResponse, error)
	Dispatch(ctx context.Context, in *DispatchNotificationRequest, opts ...grpc.CallOption) (*DispatchNotificationResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateUserSetting(ctx context.Context, in *CreateUserSettingRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateUserSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NewJobForCategory(ctx context.Context, in *NewJobForCategoryRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_NewJobForCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ApplyForJob(ctx context.Context, in *ApplyForJobRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_ApplyForJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) AcceptJob(ctx context.Context, in *AcceptJobRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_AcceptJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateStatusContract(ctx context.Context, in *UpdateStatusContractRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_UpdateStatusContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotificationDisputeForAdmin(ctx context.Context, in *NotificationDisputeForAdminRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotificationDisputeForAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotificationDisputeResolution(ctx context.Context, in *NotificationDisputeResolutionRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotificationDisputeResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ChangeBalance(ctx context.Context, in *ChangeBalanceRequest, opts ...grpc.CallOption) (*NotiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotiResponse)
	err := c.cc.Invoke(ctx, NotificationService_ChangeBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Dispatch(ctx context.Context, in *DispatchNotificationRequest, opts ...grpc.CallOption) (*DispatchNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	CreateUserSetting(context.Context, *CreateUserSettingRequest) (*NotiResponse, error)
	NewJobForCategory(context.Context, *NewJobForCategoryRequest) (*NotiResponse, error)
	ApplyForJob(context.Context, *ApplyForJobRequest) (*NotiResponse, error)
	AcceptJob(context.Context, *AcceptJobRequest) (*NotiResponse, error)
	UpdateStatusContract(context.Context, *UpdateStatusContractRequest) (*NotiResponse, error)
	NotificationDisputeForAdmin(context.Context, *NotificationDisputeForAdminRequest) (*NotiResponse, error)
	NotificationDisputeResolution(context.Context, *NotificationDisputeResolutionRequest) (*NotiResponse, error)
	ChangeBalance(context.Context, *ChangeBalanceRequest) (*NotiResponse, error)
	Dispatch(context.Context, *DispatchNotificationRequest) (*DispatchNotificationResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) CreateUserSetting(context.Context, *CreateUserSettingRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserSetting not implemented")
}
func (UnimplementedNotificationServiceServer) NewJobForCategory(context.Context, *NewJobForCategoryRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewJobForCategory not implemented")
}
func (UnimplementedNotificationServiceServer) ApplyForJob(context.Context, *ApplyForJobRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyForJob not implemented")
}
func (UnimplementedNotificationServiceServer) AcceptJob(context.Context, *AcceptJobRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptJob not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateStatusContract(context.Context, *UpdateStatusContractRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatusContract not implemented")
}
func (UnimplementedNotificationServiceServer) NotificationDisputeForAdmin(context.Context, *NotificationDisputeForAdminRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotificationDisputeForAdmin not implemented")
}
func (UnimplementedNotificationServiceServer) NotificationDisputeResolution(context.Context, *NotificationDisputeResolutionRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotificationDisputeResolution not implemented")
}
func (UnimplementedNotificationServiceServer) ChangeBalance(context.Context, *ChangeBalanceRequest) (*NotiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeBalance not implemented")
}
func (UnimplementedNotificationServiceServer) Dispatch(context.Context, *DispatchNotificationRequest) (*DispatchNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_CreateUserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateUserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateUserSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateUserSetting(ctx, req.(*CreateUserSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NewJobForCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewJobForCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NewJobForCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NewJobForCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NewJobForCategory(ctx, req.(*NewJobForCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ApplyForJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyForJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ApplyForJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ApplyForJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ApplyForJob(ctx, req.(*ApplyForJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_AcceptJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).AcceptJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_AcceptJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).AcceptJob(ctx, req.(*AcceptJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateStatusContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateStatusContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateStatusContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateStatusContract(ctx, req.(*UpdateStatusContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotificationDisputeForAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationDisputeForAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotificationDisputeForAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotificationDisputeForAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotificationDisputeForAdmin(ctx, req.(*NotificationDisputeForAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotificationDisputeResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationDisputeResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotificationDisputeResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotificationDisputeResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotificationDisputeResolution(ctx, req.(*NotificationDisputeResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ChangeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ChangeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ChangeBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ChangeBalance(ctx, req.(*ChangeBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Dispatch(ctx, req.(*DispatchNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common_proto.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserSetting",
			Handler:    _NotificationService_CreateUserSetting_Handler,
		},
		{
			MethodName: "NewJobForCategory",
			Handler:    _NotificationService_NewJobForCategory_Handler,
		},
		{
			MethodName: "ApplyForJob",
			Handler:    _NotificationService_ApplyForJob_Handler,
		},
		{
			MethodName: "AcceptJob",
			Handler:    _NotificationService_AcceptJob_Handler,
		},
		{
			MethodName: "UpdateStatusContract",
			Handler:    _NotificationService_UpdateStatusContract_Handler,
		},
		{
			MethodName: "NotificationDisputeForAdmin",
			Handler:    _NotificationService_NotificationDisputeForAdmin_Handler,
		},
		{
			MethodName: "NotificationDisputeResolution",
			Handler:    _NotificationService_NotificationDisputeResolution_Handler,
		},
		{
			MethodName: "ChangeBalance",
			Handler:    _NotificationService_ChangeBalance_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _NotificationService_Dispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common-proto/notification.proto",
}
