// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: common-proto/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EscrowStatus int32

const (
	EscrowStatus_ESCROW_STATUS_HELD             EscrowStatus = 0
	EscrowStatus_ESCROW_STATUS_RELEASED         EscrowStatus = 1
	EscrowStatus_ESCROW_STATUS_REFUNDED         EscrowStatus = 2
	EscrowStatus_ESCROW_STATUS_PARTIAL_REFUNDED EscrowStatus = 3
	EscrowStatus_ESCROW_STATUS_DISPUTED         EscrowStatus = 4
)

// Enum value maps for EscrowStatus.
var (
	EscrowStatus_name = map[int32]string{
		0: "ESCROW_STATUS_HELD",
		1: "ESCROW_STATUS_RELEASED",
		2: "ESCROW_STATUS_REFUNDED",
		3: "ESCROW_STATUS_PARTIAL_REFUNDED",
		4: "ESCROW_STATUS_DISPUTED",
	}
	EscrowStatus_value = map[string]int32{
		"ESCROW_STATUS_HELD":             0,
		"ESCROW_STATUS_RELEASED":         1,
		"ESCROW_STATUS_REFUNDED":         2,
		"ESCROW_STATUS_PARTIAL_REFUNDED": 3,
		"ESCROW_STATUS_DISPUTED":         4,
	}
)

func (x EscrowStatus) Enum() *EscrowStatus {
	p := new(EscrowStatus)
	*p = x
	return p
}

func (x EscrowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EscrowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_payment_proto_enumTypes[0].Descriptor()
}

func (EscrowStatus) Type() protoreflect.EnumType {
	return &file_common_proto_payment_proto_enumTypes[0]
}

func (x EscrowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EscrowStatus.Descriptor instead.
func (EscrowStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{0}
}

type WalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletRequest) Reset() {
	*x = WalletRequest{}
	mi := &file_common_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletRequest) ProtoMessage() {}

func (x *WalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletRequest.ProtoReflect.Descriptor instead.
func (*WalletRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *WalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_common_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *WalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EscrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,3,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        EscrowStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=common_proto.EscrowStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowRequest) Reset() {
	*x = EscrowRequest{}
	mi := &file_common_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowRequest) ProtoMessage() {}

func (x *EscrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowRequest.ProtoReflect.Descriptor instead.
func (*EscrowRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *EscrowRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *EscrowRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *EscrowRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *EscrowRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *EscrowRequest) GetStatus() EscrowStatus {
	if x != nil {
		return x.Status
	}
	return EscrowStatus_ESCROW_STATUS_HELD
}

type EscrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowResponse) Reset() {
	*x = EscrowResponse{}
	mi := &file_common_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowResponse) ProtoMessage() {}

func (x *EscrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowResponse.ProtoReflect.Descriptor instead.
func (*EscrowResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *EscrowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_common_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalanceRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_common_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_common_proto_payment_proto protoreflect.FileDescriptor

const file_common_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x1acommon-proto/payment.proto\x12\fcommon_proto\"(\n" +
	"\rWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0eWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc2\x01\n" +
	"\rEscrowRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rfreelancer_id\x18\x03 \x01(\tR\ffreelancerId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.common_proto.EscrowStatusR\x06status\"*\n" +
	"\x0eEscrowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"'\n" +
	"\x0fBalanceResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid*\x9e\x01\n" +
	"\fEscrowStatus\x12\x16\n" +
	"\x12ESCROW_STATUS_HELD\x10\x00\x12\x1a\n" +
	"\x16ESCROW_STATUS_RELEASED\x10\x01\x12\x1a\n" +
	"\x16ESCROW_STATUS_REFUNDED\x10\x02\x12\"\n" +
	"\x1eESCROW_STATUS_PARTIAL_REFUNDED\x10\x03\x12\x1a\n" +
	"\x16ESCROW_STATUS_DISPUTED\x10\x042\xbf\x02\n" +
	"\x0ePaymentService\x12I\n" +
	"\fCreateWallet\x12\x1b.common_proto.WalletRequest\x1a\x1c.common_proto.WalletResponse\x12K\n" +
	"\fCheckBalance\x12\x1c.common_proto.BalanceRequest\x1a\x1d.common_proto.BalanceResponse\x12I\n" +
	"\fCreateEscrow\x12\x1b.common_proto.EscrowRequest\x1a\x1c.common_proto.EscrowResponse\x12J\n" +
	"\rProcessEscrow\x12\x1b.common_proto.EscrowRequest\x1a\x1c.common_proto.EscrowResponseB\fZ\n" +
	"/paymentpbb\x06proto3"

var (
	file_common_proto_payment_proto_rawDescOnce sync.Once
	file_common_proto_payment_proto_rawDescData []byte
)

func file_common_proto_payment_proto_rawDescGZIP() []byte {
	file_common_proto_payment_proto_rawDescOnce.Do(func() {
		file_common_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_payment_proto_rawDesc), len(file_common_proto_payment_proto_rawDesc)))
	})
	return file_common_proto_payment_proto_rawDescData
}

var file_common_proto_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_payment_proto_goTypes = []any{
	(EscrowStatus)(0),       // 0: common_proto.EscrowStatus
	(*WalletRequest)(nil),   // 1: common_proto.WalletRequest
	(*WalletResponse)(nil),  // 2: common_proto.WalletResponse
	(*EscrowRequest)(nil),   // 3: common_proto.EscrowRequest
	(*EscrowResponse)(nil),  // 4: common_proto.EscrowResponse
	(*BalanceRequest)(nil),  // 5: common_proto.BalanceRequest
	(*BalanceResponse)(nil), // 6: common_proto.BalanceResponse
}
var file_common_proto_payment_proto_depIdxs = []int32{
	0, // 0: common_proto.EscrowRequest.status:type_name -> common_proto.EscrowStatus
	1, // 1: common_proto.PaymentService.CreateWallet:input_type -> common_proto.WalletRequest
	5, // 2: common_proto.PaymentService.CheckBalance:input_type -> common_proto.BalanceRequest
	3, // 3: common_proto.PaymentService.CreateEscrow:input_type -> common_proto.EscrowRequest
	3, // 4: common_proto.PaymentService.ProcessEscrow:input_type -> common_proto.EscrowRequest
	2, // 5: common_proto.PaymentService.CreateWallet:output_type -> common_proto.WalletResponse
	6, // 6: common_proto.PaymentService.CheckBalance:output_type -> common_proto.BalanceResponse
	4, // 7: common_proto.PaymentService.CreateEscrow:output_type -> common_proto.EscrowResponse
	4, // 8: common_proto.PaymentService.ProcessEscrow:output_type -> common_proto.EscrowResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_payment_proto_init() }
func file_common_proto_payment_proto_init() {
	if File_common_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_payment_proto_rawDesc), len(file_common_proto_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_payment_proto_goTypes,
		DependencyIndexes: file_common_proto_payment_proto_depIdxs,
		EnumInfos:         file_common_proto_payment_proto_enumTypes,
		MessageInfos:      file_common_proto_payment_proto_msgTypes,
	}.Build()
	File_common_proto_payment_proto = out.File
	file_common_proto_payment_proto_goTypes = nil
	file_common_proto_payment_proto_depIdxs = nil
}
